### ISSUE TITLE
runner_config problem

### ISSUE THREAD

**Issue by lostandfoud** [lfbear/ansible-api#19]
"error": "status_handler() got an unexpected keyword argument 'runner_config'",

this is the stack:
```
2019-03-24 18:17:56 | ERROR - status_handler() got an unexpected keyword argument 'runner_config'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ansible_api/controller.py", line 162, in post
    response = await loop.run_in_executor(pool, self.run, hosts, name, yml_file, my_vars, cb)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ansible_api/controller.py", line 177, in run
    event_handler=cb.event_handler, status_handler=cb.status_handler
  File "/usr/local/lib/python3.7/dist-packages/ansible_runner/interface.py", line 159, in run
    r.run()
  File "/usr/local/lib/python3.7/dist-packages/ansible_runner/runner.py", line 89, in run
    self.status_callback('starting')
  File "/usr/local/lib/python3.7/dist-packages/ansible_runner/runner.py", line 82, in status_callback
    self.status_handler(status_data, runner_config=self.config)
TypeError: status_handler() got an unexpected keyword argument 'runner_config'

```

ansible 2.7.9

**Comment by lostandfoud** [comment]
you can look here:
https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner.py#L82

**Comment by lfbear** [comment]
thanks
