### ISSUE TITLE
 ERROR  argument of type NoneType is not iterable

### ISSUE THREAD

**Issue by opcache** [lfbear/ansible-api#24]
2019-10-10 06:14:40 | ERROR - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_api/controller.py", line 106, in post
    response = await loop.run_in_executor(pool, self.run, target, name, module, arg, cb)
  File "/usr/local/python37/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_api/controller.py", line 119, in run
    event_handler=cb.event_handler, status_handler=cb.status_handler
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/interface.py", line 162, in run
    r.run()
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/runner.py", line 177, in run
    searchwindowsize=100)
  File "/usr/local/python37/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/python37/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/python37/lib/python3.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/python37/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 500, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/python37/lib/python3.7/site-packages/pexpect/spawnbase.py", line 179, in read_nonblocking
    self._log(s, 'read')
  File "/usr/local/python37/lib/python3.7/site-packages/pexpect/spawnbase.py", line 130, in _log
    second_log.write(s)
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/utils.py", line 251, in write
    event_data = self._emit_event(value[:match.start()], event_data)
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/utils.py", line 326, in _emit_event
    self._event_callback(event_data)
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/runner.py", line 68, in event_callback
    should_write = self.event_handler(event_data)
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_api/callback.py", line 31, in event_handler
    detail = rpt.detail()
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_api/report.py", line 88, in detail
    if o in detail['res']:
TypeError: argument of type 'NoneType' is not iterable
[2019-10-10 06:14:40 +0000] - (sanic.access)[INFO][192.168.56.1:55071]: POST http://192.168.56.102:8765/command  200 62
2019-10-10 06:14:40 | INFO - 
[2019-10-10 06:14:45 +0000] [522] [DEBUG] KeepAlive Timeout. Closing connection.
2019-10-10 06:14:45 | DEBUG - KeepAlive Timeout. Closing connection

**Comment by ppabc** [comment]
callback.py  里面这句def status_handler(self, data, runner_config=None):
貌似有错误  runner_config=None

**Comment by opcache** [comment]
callback.py 里面这句def status_handler(self, data, runner_config=None):
貌似有错误 runner_config=None

**Comment by lfbear** [comment]
please show the version of ansible and ansible-runner (pip/pip3 list| grep ansibile)

**Comment by opcache** [comment]
[root@aaa]# pip3 list| grep ansible
ansible           2.8.5    
ansible-api       0.5.0    
ansible-runner    1.4.2

**Comment by opcache** [comment]
[root@aaa]# pip3 list| grep ansible
 ansible           2.8.5
 ansible-api       0.5.0
 ansible-runner    1.4.2
感谢回复！




------------------ 原始邮件 ------------------
发件人: "little flying bear"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 上午8:45
收件人: "lfbear/ansible-api"<ansible-api@noreply.github.com>;
抄送: "小哈"<7529997@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lfbear/ansible-api]  ERROR  argument of type NoneType is notiterable (#24)




please show the version of ansible and ansible-runner (pip/pip3 list| grep ansibile)

**Comment by opcache** [comment]
感谢回复，我ansible  2.6.4  用这个版本正常了

**Comment by jmm94** [comment]
pip3 list| grep ansible
ansible                2.9.6
ansible-api            0.5.0
ansible-runner         1.4.6

ERROR status_handler() got an unexpected keyword argument runner_config #25

a possible next fix for this issue ?

**Comment by slefol** [comment]
I am same issue with :
ansible 2.9.6
ansible-api 0.5.0
ansible-runner 1.4.6

a possible next fix for this issue ?

**Comment by slefol** [comment]
> I am same issue with :
> ansible 2.9.6
> ansible-api 0.5.0
> ansible-runner 1.4.6
> 
> a possible next fix for this issue ?

i installed from the command 'python setup.py install' and it's works !
(python-3.7.3, ansible-2.10.3, ansible_runner-1.4.6, ansible_api-0.5.1)
