### ISSUE TITLE
ERROR status_handler() got an unexpected keyword argument  runner_config 

### ISSUE THREAD

**Issue by opcache** [lfbear/ansible-api#25]
2019-10-10 07:04:32 | ERROR - status_handler() got an unexpected keyword argument 'runner_config'
Traceback (most recent call last):
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_api/controller.py", line 106, in post
    response = await loop.run_in_executor(pool, self.run, target, name, module, arg, cb)
  File "/usr/local/python37/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_api/controller.py", line 119, in run
    event_handler=cb.event_handler, status_handler=cb.status_handler
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/interface.py", line 162, in run
    r.run()
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/runner.py", line 93, in run
    self.status_callback('starting')
  File "/usr/local/python37/lib/python3.7/site-packages/ansible_runner/runner.py", line 86, in status_callback
    self.status_handler(status_data, runner_config=self.config)
TypeError: status_handler() got an unexpected keyword argument 'runner_config'

这个是要配置什么？

**Comment by lfbear** [comment]
please show me the version of ansible and ansible-runner

**Comment by lfbear** [comment]
same as #24
