### ISSUE TITLE
启动报这个错误

### ISSUE THREAD

**Issue by ppabc** [lfbear/ansible-api#9]
ansible-api -c /etc/ansible/api.cfg -d
Traceback (most recent call last):
  File "/usr/bin/ansible-api", line 18, in <module>
    from ansible_api.webapi import WebApi
  File "/usr/lib/python2.7/site-packages/ansible_api/webapi.py", line 16, in <module>
    from ansible_api import controller
  File "/usr/lib/python2.7/site-packages/ansible_api/controller.py", line 36, in <module>
    executor = futures.ThreadPoolExecutor(int(Config.Get('thread_pool_size')))
ValueError: invalid literal for int() with base 10: ''
[root@bogon ansible-api]#

**Comment by ppabc** [comment]
ansible-api -c /etc/ansible/api.cfg -d
Info: Load config file from /etc/ansible/api.cfg
Ansible API is running at Daemon Mode

Traceback (most recent call last):
  File "/usr/bin/ansible-api", line 46, in <module>
    Tool.init_logger(log_path)
AttributeError: type object 'Tool' has no attribute 'init_logger'
[root@bogon ansible-api-master]#

**Comment by ppabc** [comment]
ansible 2.3 貌似部署有问题，  换2.1后正常

**Comment by lfbear** [comment]
ansible 2.3还没适配 目前最高适配版本2.2.1 抽空的时候会做个适配的

**Comment by lfbear** [comment]
Already updated
